// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "jwt-auth/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// CreateOrUpdate provides a mock function with given fields: ctx, token
func (_m *Repo) CreateOrUpdate(ctx context.Context, token entities.RefreshToken) error {
	ret := _m.Called(ctx, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTokenByID provides a mock function with given fields: ctx, userID
func (_m *Repo) GetTokenByID(ctx context.Context, userID string) (entities.RefreshToken, error) {
	ret := _m.Called(ctx, userID)

	var r0 entities.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.RefreshToken, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.RefreshToken); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(entities.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
